# Generated by Django 4.1.2 on 2023-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_group_specialization_remove_group_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textField', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLectureAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.teacher')),
            ],
        ),
    ]
