# Generated by Django 4.1.2 on 2023-04-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_course_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherlectureassessment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teacherlectureassessment',
            name='average',
        ),
        migrations.RemoveField(
            model_name='teacherlectureassessment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='teacherlectureassessment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='teacherlectureassessment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='teacherlectureassessment',
            name='total',
        ),
    ]
