# Generated by Django 4.1.2 on 2023-04-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_teacherlectureassessment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100)),
                ('num', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('fields', models.ManyToManyField(to='poll.assessmentfield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherLectureAssessment',
        ),
    ]
