# Generated by Django 4.1.2 on 2023-04-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_assessmentfield_teacherassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.dayschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.subject')),
            ],
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.lesson'),
        ),
    ]
