# Generated by Django 4.1.2 on 2023-04-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_student_score_teacher_score_lessontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='num',
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(default='Лекція', max_length=20),
        ),
        migrations.DeleteModel(
            name='LessonType',
        ),
    ]
