# Generated by Django 4.1.2 on 2023-04-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.weekschedule'),
        ),
    ]
