# Generated by Django 4.1.2 on 2023-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_group_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayschedule',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='days',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='lessons',
            field=models.ManyToManyField(to='poll.lesson'),
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='days',
            field=models.ManyToManyField(to='poll.dayschedule'),
        ),
    ]
