# Generated by Django 4.1.2 on 2023-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_remove_dayschedule_lessons_remove_weekschedule_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
