# Generated by Django 4.1.2 on 2023-04-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_student_user_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassessment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.student'),
        ),
        migrations.AlterField(
            model_name='teacherassessment',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
